<?php

/**
 * Dizkus
 *
 * @copyright (c) 2001-now, Dizkus Development Team
 * @link https://github.com/zikula-modules/Dizkus
 * @license GNU/GPL - http://www.gnu.org/copyleft/gpl.html
 * @package Dizkus
 */

namespace Dizkus\Controller;

use ModUtil;
use System;
use LogUtil;
use SecurityUtil;
use FormUtil;
use Dizkus\Entity\RankEntity;

class AdminController extends \Zikula_AbstractController
{

    public function postInitialize()
    {
        $this->view->setCaching(false)->add_core_data();
    }

    /**
     * the main administration function
     *
     */
    public function indexAction()
    {
        $url = ModUtil::url($this->name, 'admin', 'tree');

        return System::redirect($url);
    }

    /**
     * Change forum order
     *
     * Move up or down a forum in the tree
     *
     * @return boolean
     */
    public function changeForumOrderAction()
    {
        $action = $this->request->query->get('action', 'moveUp');
        $forumId = $this->request->query->get('forum', null);
        if (empty($forumId)) {
            return LogUtil::registerArgsError();
        }
        $repo = $this->entityManager->getRepository('Dizkus\Entity\ForumEntity');
        $forum = $repo->find($forumId);
        if ($action == 'moveUp') {
            $repo->moveUp($forum, true);
        } else {
            $repo->moveDown($forum, true);
        }
        $this->entityManager->flush();
        $url = ModUtil::url($this->name, 'admin', 'tree');

        return System::redirect($url);
    }

    /**
     * preferences
     *
     */
    public function preferencesAction()
    {
        if (!SecurityUtil::checkPermission('Dizkus::', '::', ACCESS_ADMIN)) {
            return LogUtil::registerPermissionError();
        }
        // Create output object
        $form = FormUtil::newForm('Dizkus', $this);
        // Return the output that has been generated by this function
        return $form->execute('admin/preferences.tpl', new Dizkus_Form_Handler_Admin_Prefs());
    }

    /**
     * syncforums
     */
    public function syncforumsAction()
    {
        $showstatus = !$this->request->request->get('silent', 0);
        if (!SecurityUtil::checkPermission('Dizkus::', '::', ACCESS_ADMIN)) {
            return LogUtil::registerPermissionError();
        }
        $succesful = ModUtil::apiFunc('Dizkus', 'Sync', 'forums');
        if ($showstatus && $succesful) {
            LogUtil::registerStatus($this->__('Done! Synchronized forum index.'));
        } else {
            return LogUtil::registerError($this->__('Error synchronizing forum index'));
        }
        $succesful = ModUtil::apiFunc('Dizkus', 'Sync', 'topics');
        if ($showstatus && $succesful) {
            LogUtil::registerStatus($this->__('Done! Synchronized topics.'));
        } else {
            return LogUtil::registerError($this->__('Error synchronizing topics.'));
        }
        $succesful = ModUtil::apiFunc('Dizkus', 'Sync', 'posters');
        if ($showstatus && $succesful) {
            LogUtil::registerStatus($this->__('Done! Synchronized posts counter.'));
        } else {
            return LogUtil::registerError($this->__('Error synchronizing posts counter.'));
        }

        return System::redirect(ModUtil::url('Dizkus', 'admin', 'main'));
    }

    /**
     * ranks
     */
    public function ranksAction()
    {
        if (!SecurityUtil::checkPermission('Dizkus::', '::', ACCESS_ADMIN)) {
            return LogUtil::registerPermissionError();
        }
        $submit = $this->request->getPost()->filter('submit', 2);
        $ranktype = $this->request->getGet()->filter('ranktype', RankEntity::TYPE_POSTCOUNT, FILTER_SANITIZE_NUMBER_INT);
        if ($submit == 2) {
            list($rankimages, $ranks) = ModUtil::apiFunc($this->name, 'Rank', 'getAll', array('ranktype' => $ranktype));
            $this->view->assign('ranks', $ranks);
            $this->view->assign('ranktype', $ranktype);
            $this->view->assign('rankimages', $rankimages);
            if ($ranktype == 0) {
                return $this->view->fetch('admin/ranks.tpl');
            } else {
                return $this->view->fetch('admin/honoraryranks.tpl');
            }
        } else {
            $ranks = $this->request->getPost()->filter('ranks', '', FILTER_SANITIZE_STRING);
            ModUtil::apiFunc($this->name, 'Rank', 'save', array('ranks' => $ranks));
        }

        return System::redirect(ModUtil::url($this->name, 'admin', 'ranks', array('ranktype' => $ranktype)));
    }

    /**
     * ranks
     */
    public function assignranksAction()
    {
        if (!SecurityUtil::checkPermission('Dizkus::', '::', ACCESS_ADMIN)) {
            return LogUtil::registerPermissionError();
        }
        $form = FormUtil::newForm('Dizkus', $this);

        return $form->execute('admin/assignranks.tpl', new Dizkus\Form\Handler\Admin\AssignRanks());
    }

    /**
     * tree
     *
     * Show the forum tree.
     *
     * @return string
     */
    public function treeAction()
    {
        if (!SecurityUtil::checkPermission('Dizkus::', '::', ACCESS_ADMIN)) {
            return LogUtil::registerPermissionError();
        }
        $tree = $this->entityManager->getRepository('Dizkus\Entity\ForumEntity')->childrenHierarchy(null, false);

        return $this->view->assign('tree', $tree)->fetch('admin/tree.tpl');
    }

    /**
     *
     */
    public function modifyForumAction()
    {
        $form = FormUtil::newForm('Dizkus', $this);

        return $form->execute('admin/modifyforum.tpl', new Dizkus\Form\Handler\Admin\ModifyForum());
    }

    /**
     *
     */
    public function deleteforumAction()
    {
        $form = FormUtil::newForm('Dizkus', $this);

        return $form->execute('admin/deleteforum.tpl', new Dizkus\Form\Handler\Admin\DeleteForum());
    }

    /**
     * managesubscriptions
     *
     */
    public function manageSubscriptionsAction()
    {
        $form = FormUtil::newForm('Dizkus', $this);

        return $form->execute('admin/managesubscriptions.tpl', new Dizkus\Form\Handler\Admin\ManageSubscriptions());
    }

}